apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-cfg
  namespace: monitoring
data:
  file: |
    global:
      resolve_timeout: "1m"

    route:
      receiver: telegram
      group_by: 
      - alertname
      continue: false
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: 'telegram'
      telegram_configs:
      - send_resolved: true
        bot_token: 'your bot token'
        chat_id: 'your bot id'
        api_url: 'https://api.telegram.org'
        message: 'you message'
    #parse_mode: "MarkdownV2"