apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: bitnami/alertmanager:0.24.0
        resources: 
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9093
        volumeMounts:
          - mountPath: /opt/bitnami/alertmanager/conf/config.yml
            subPath: file
            name: mnt
      volumes:
        - name: mnt
          configMap:
            name: alertmanager-cfg
